apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-color
  labels:
    tier: frontend
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 6
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: webapp-color
          image: 324761312512.dkr.ecr.us-east-1.amazonaws.com/webapp-color:latest
          ports:
            - containerPort: 8080
