apiVersion: v1
kind: Service
metadata:
  name: webapp-color-svc
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
